### ISSUE TITLE
How do you send and receive an array of bytes over the network?

### ISSUE THREAD

**Issue by valkyrienyanko** [valkyrienyanko/Prototype#1]
## Send
I want to send an array of bytes which contains a data `type` and the `x`, `y`, `z` position of a player. The data `type` tells us that this is of 'position' data, this value could be `1`. For position data, `x`, `y`, and `z` are integers and can be values such as `1500`, `20`, `-3000`.

With the [BitConverter](https://docs.microsoft.com/en-us/dotnet/api/system.bitconverter?view=netcore-3.1), we can convert all our integers to byte arrays.

I found that the Unity `DataStreamWriter` class has a `public bool WriteBytes(NativeArray<byte> value);` method, so we can use that to send the bytes of data over the network.

Below is what I have so far.
https://github.com/valkyrienyanko/Prototype/blob/4762ead183cbb3c2d23dfcd4519318e55127ba59/Assets/Workspace/Scripts/Client.cs#L51-L66
I'm adding the byte arrays to a list to combine them all into one big byte array. Then I am passing that to the `new NativeArray<byte>(bytes.ToArray(), Allocator.Persistent);` and finally we write that data to the `writer`.

Note that I still have yet to see if this data makes it all in one piece on the server side.

Note that I am using the new Unity Transport Layer minimal client-server example. You can learn more about it [here](https://docs.unity3d.com/Packages/com.unity.transport@0.3/manual/workflow-client-server.html).

## Receive
I found that the DataStreamReader class has a `public void ReadBytes(NativeArray<byte> array);` and it's asking for `NativeArray<byte> array` as a param, but my question is how do you know what your going to put in there if you're already receiving the array?

**Comment by valkyrienyanko** [comment]
Started to look back at my previous projects and found this. Going to try it out now.
https://github.com/valkyrienyanko/Networking-Unity-Prototype-Deprecated/blob/13ad3e9e6c0dbe919d111a7fa3d361717d9eaac1/Client/Assets/Scripts/Client.cs#L240-L245

**Comment by valkyrienyanko** [comment]
Solved :-)

Read the documentation to understand. https://docs.unity3d.com/Packages/com.unity.transport@0.3/api/Unity.Networking.Transport.DataStreamReader.html

Edit* I never knew the docs existed until now!

I'll commit the new changes to the repo sooner or later and you can see for yourself.

**Comment by valkyrienyanko** [comment]
The following commit fixes everything relating to this issue.
b49fdc5fdec843cbe402d6e86a8e0017231ef513

**Comment by HarryBGamer2570** [comment]
mann, 10Q veri mach, 🙏 for sharing the git commit. i was trying 2 whole days trying to send and receive byte**S** between the client and server 🙏🙏 at some point i even started trying to convert a byte[] into a byte* with "unsafe" code
